### PR TITLE
A few small changes

### PR DESCRIPTION
**Pull request by ParmuzinAlexander**

### CODE REVIEW

**Comment by yewang** [comment]
Thank you for the style contributions in your pull request!

Are you okay with releasing your work under MIT license? Would you like to be listed in the readme as a contributor?

**Comment by ParmuzinAlexander** [comment]
Yes. No need I didn't do anything.

**Comment by ParmuzinAlexander** [comment]
Maybe I shouldn't have deleted the spaces, check it.

**Comment by yewang** [comment]
I think it would be better to try to break up some of these changes into separate pull requests. There are a lot stylistic changes, and not all that I prefer.

When it comes to designing new color themes, I think it would be better to just add additional alternatives, rather than changing existing ones, e.g., we could have several different dark themes, rather that just one. I personally prefer my original dark theme.

**Comment by ParmuzinAlexander** [comment]
OK, just use the changes you agree with. I don't know very well how to use github.

**Pull request closed without merging**
